@startuml 
skinparam packageStyle rect

left to right direction
actor Bob
rectangle LocalServer {
usecase UC_einloggen as "Einloggen"

Bob -- UC_einloggen
}

rectangle RemoteServer {

}

UC_einloggen -- RemoteServer 


@enduml
