
@startuml 
skinparam packageStyle rect

left to right direction
actor Bob
rectangle LocalServer {
usecase UC_registrieren as "Registrieren"

Bob -- UC_registrieren
}

rectangle RemoteServer {

}

UC_registrieren -- RemoteServer 


@enduml
